ganesh/urls.py
from django.urls import path
from ganesh import views
from rest_framework.routers import DefaultRouter
from ganesh.credit_RestApi import credbasicdetailformviewsets,creditDetailviewsets



router=DefaultRouter()
router.register('api_basicdetail',credbasicdetailformviewsets,basename='api_basicdetail'),
router.register('api_credit_appli',creditDetailviewsets,basename='api_credit_appli'),



urlpatterns = [
    path('crebasicdetail/', views.crebasicdetails, name='crebasicdetail'),
    path('cre-fetch-credit-report/', views.cre_fetch_credit_report, name='crefetchcreditreport'),

    path('credit/', views.credit_add, name='credit'),
    path('document_add/<str:application_id>/', views.credit_document_add, name='document_add'),
    path('success/<str:application_id>', views.ccsuccess, name='ccsuccess'), 
    path('credit/<int:pk>/update/', views.update_cred_detail_view, name='update_credit_detail'),
    path('update-document/<int:instance_id>/', views.update_cred_document_detail_view, name='update_document'),
    path('table_view/', views.credit_table_view, name='personal_detail_list'),

    path('credit/<int:pk>/view/', views.view_credit_appli, name='view_credit_appli'),

    path('document_view/', views.view_credit_documents, name='view_documents'),







    path('getByRefCode/<str:refCode>',creditDetailviewsets.as_view({"get":"getByRefCode"}),name="get-ref-code"),
    path('getBasicdetailapplicationid/<str:mobileNumber>',credbasicdetailformviewsets.as_view({"get":"getApplicationId"}),name="getApplicationId"),

]

ravi/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views

from ravi.hlapi import CustomerViewSet,PlViewSet
from rest_framework.routers import DefaultRouter


router=DefaultRouter()
router.register('hlapi',CustomerViewSet,basename='hlapi')
router.register('plapi',PlViewSet,basename='plapi')



urlpatterns = [

    # Personal Details URLs
    path('personal/', views.personal_detail_view, name='personal'),  # View personal details
    path('personaldoc/<str:application_id>/', views.document_details_view, name='document_detail'),  # Upload personal documents
    path('personal/<int:pk>/update/', views.update_personal_detail_view, name='update_personal_detail'),  # Update personal details
    path('personal/<int:pk>/view/', views.view_personal_detail_view, name='view_personal_detail'),  # View personal detail
    path('personallist/', views.personal_detail_list_view, name='personal_detail_list'),  # List personal details

    # Document Management URLs
    path('document/<int:instance_id>/update/', views.update_document_detail_view, name='update_document_detail'),  # Update document details
    path('document/uploads/', views.document_upload_list_view, name='document_upload_list'),  # List uploaded documents
    path('document/upload/<int:pk>/view/', views.view_documents_view, name='view_documents'),  # View a specific document

    # Home/Customer Profile URLs
    path('home/', views.customer_profile_view, name='customer_profile'),  # View a specific customer profile
    path('home/<int:pk>/update/', views.update_customer_profile_view, name='update_customer_profile'),  # Update a customer profile
    path('home/<int:pk>/view/', views.view_customer_profile_view, name='view_customer_profile'),  # View a specific customer profile
    path('homelist/', views.customer_profile_list_view, name='customer_profile_list'),  # List customer profiles

    # Applicant Document URLs
    path('homedoc/<str:application_id>/', views.applicant_document_create_view, name='applicant_document_create'),  # Create an applicant document
    path('applicant/<int:instance_id>/update/', views.update_applicant_document_view, name='update_applicant_document'),  # Update an applicant document
    path('applicant/documents/', views.applicant_document_list_view, name='applicant_document_list'),  # List applicant documents
    path('applicant/<int:pk>/view/', views.view_applicant_document_view, name='view_applicant_document'),  # View a specific applicant document

    # Success page
    path('success/<str:application_id>/', views.success, name='success'),  # Success page after submission

    # Dashboard
    path('dashboard/', views.dashboard, name='dashboard'),  # Dashboard view

    # Verification for Personal and Home Customers
    path('perstatus/<int:instance_id>/', views.personal_verification_add, name='personal_verification_add'),  # Add personal verification
    path('perstatus/<int:instance_id>/update/', views.update_plverify, name='update_personal_verify'),  # Update personal verification
    path('perstatus/<int:instance_id>/view/', views.personalcustomerverify, name='view_personal_verify'),  # View personal verification
    path('applyhome/<int:instance_id>/', views.home_verification_add, name='applyhome'),  # Add home verification
    path('applyhome/<int:instance_id>/update/', views.update_hlverify, name='update_home_verify'),  # Update home verification
    path('applyhome/<int:instance_id>/view/', views.homecustomerverify, name='view_home_verify'),  # View home verification

    # Authentication URLs
    path('logout/', views.custom_logout, name='logout'),  # Logout
    path('register/', views.register, name='register'),  # Register a new user
    path('employee_login/', views.Loginemployee, name='employee_login'),  # Employee login
    path('homelogin/', views.Loginhome, name='homelogin'),  # Home login
    path('homeregister/', views.homeregister, name='homeregister'),  # Home register

    # Basic Detail Views
    path('perbasicdetail/', views.basicdetailspl, name='personalbasicdetail'),
    path('pl-fetch-credit-report/', views.pl_fetch_credit_report, name='plfetchcreditreport'),
  # Personal basic detail
    path('homebasicdetail/', views.basicdetailhl, name='homebasicdetail'),
    path('hl-fetch-credit-report/', views.hl_fetch_credit_report, name='hlfetchcreditreport'),
  # Home basic detail

    path('disbursement/<int:verification_id>/', views.hldisbursement_details, name='hldisbursement_details'),#disbursement
    path('hldisbursement-summary/', views.hldisbursement_summary, name='hldisbursement_summary'),#disbursement-summary
    path('hlsuccess/<str:application_id>', views.hlsuccess, name='hlsuccess'),#success
    path('rejected/<str:status>',views.rejected_hl,name='hlpage'),#rejected

    
    path('pldisbursement/<int:verification_id>/', views.pldisbursement_details, name='pldisbursement_details'),#disbursement
    path('pldisbursement-summary/', views.pldisbursement_summary, name='pldisbursement_summary'),#disbursement-summary
    path('plsuccess/<str:application_id>', views.plsuccess, name='plsuccess'),#success
    path('rejected/<str:status>',views.rejected_pl,name='plpage'),#rejected
    

    path('',include(router.urls))


]


    

slnone/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('anusha.urls')),
    path('pl/', include('ravi.urls')),
    path('el/', include('bhanu.urls')),
    path('cl/', include('seetha.urls')),
    path('cc/', include('ganesh.urls')),
    path('bl/', include('business.urls')),  # Include SLNProject URLs
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns+=static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)

ganesh/models.py
from django.db import models
from django.core.validators import EmailValidator
import random
import string
import re
from django.core.exceptions import ValidationError
from django.utils import timezone
from django.db.models import Max



def validate_only_letters(value):
    if not value.isalpha():
        raise ValidationError('Only letters are allowed.')
    
def validate_pan(value):
    pattern = r'^[A-Z]{5}[0-9]{4}[A-Z]{1}$'
    if not re.match(pattern, value):
        raise ValidationError('Invalid PAN number format')

def validate_mobile_number(value):
    pattern = r'^\+?[1-9]\d{1,14}$'
    if not re.match(pattern, value) or len(value) < 10:
        raise ValidationError('Invalid mobile number format. Must be at least 10 digits long.')
    if len(value) > 15:
        raise ValidationError('Mobile number cannot be more than 15 digits long.')

def validate_aadhar_number(value):
    pattern = r'^\d{12}$'
    if not re.match(pattern, value):
        raise ValidationError('Invalid Aadhar number format')

def validate_pincode(value):
    pattern = r'^\d{6}$'
    if not re.match(pattern, value):
        raise ValidationError('Invalid pincode format')

def validate_pincodes(value):
    if len(str(value)) != 6:
        raise ValidationError('Pincode must be 6 digits.')

def validate_amount(value):
    if len(str(value)) > 10:
        raise ValidationError('Amount must be 10 digits.')
    
def clean_aadhar_card_front(self):
        file = self.cleaned_data.get('aadhar_card_front', False)
        if file:
            if not file.name.endswith('.jpg') and not file.name.endswith('.jpeg'):
                raise ValidationError(('Only JPG/JPEG/ files are allowed.'), code='invalid')
        return file
def clean_business_proof_1(self):
        file = self.cleaned_data.get('business_proof_1', False)
        if file:
            if not file.name.endswith('.pdf'):
                raise ValidationError(('Only PDF files are allowed.'), code='invalid')
        return file
def validate_image_file(value):
    if not (value.name.endswith('.jpg') or value.name.endswith('.png') or value.name.endswith('.jpeg')):
        raise ValidationError('Only JPG/JPEG/PNG files are allowed.')


def validate_pdf_file(value):
    if not value.name.endswith('.pdf'):
        raise ValidationError('Only PDF files are allowed.')
def validate_date(value):
    if value > timezone.now().date():
        raise ValidationError('Date cannot be in the future.')
def validate_gst_number(value):
    gst_regex = re.compile(r'^[0-9]{2}[A-Z]{5}[0-9]{4}[A-Z]{1}[1-9A-Z]{1}[Z]{1}[0-9A-Z]{1}$')
    if not gst_regex.match(value):
        raise ValidationError('Invalid GST number format.')


from datetime import date
def validate_age(date_of_birth):
    if not isinstance(date_of_birth, date):
        raise ValidationError('Invalid date format.')
    
    today = date.today()
    age = today.year - date_of_birth.year - ((today.month, today.day) < (date_of_birth.month, date_of_birth.day))
    
    if not (18 <= age <= 70):
        raise ValidationError('Age must be between 18 and 70 years.')
def validate_address(value):
    
    has_letter = re.search(r'[A-Za-z]', value)
    has_digit = re.search(r'\d', value)

    if not (has_letter and has_digit):
        raise ValidationError('Address must contain both letters and digits.')

    
def validate_email(value):
    if "@" not in value:
        raise ValidationError('Invalid email address.')

    local_part, domain = value.split('@')
    
    if domain != "gmail.com":
        raise ValidationError('Email domain must be gmail.com.')
    
    if not re.search(r'[a-zA-Z]', local_part):
        raise ValidationError('Email must contain at least one letter before @gmail.com.')
    


class credbasicdetailform(models.Model):
    EXIST_CARD_CHOICES = [
        ('YES', 'yes'),
        ('NO', 'no'),

    ]
   
    GENDER_CHOICES = [('Male', 'Male'), ('Female', 'Female')]
    MARITAL_STATUS_CHOICES = [('Single', 'Single'), ('Married', 'Married'), ('Divorced', 'Divorced')]
    
    fname = models.CharField(max_length=50,default='')
    lname = models.CharField(max_length=50)
    Dob = models.DateField(validators=[validate_age])
    phone_number = models.BigIntegerField(unique=True)
    pan_num = models.CharField(max_length=10, validators=[validate_pan])
    Aadhar_number = models.CharField(max_length=12)
    gender = models.CharField(max_length=10, choices=GENDER_CHOICES)
    email = models.EmailField(validators=[EmailValidator()], blank=True, null=True)
    marital_status = models.CharField(max_length=10, choices=MARITAL_STATUS_CHOICES)
    otp = models.CharField(max_length=6, blank=True, null=True)
    application_id = models.CharField(max_length=100, blank=True, unique=True)
    created_at=models.DateField(auto_now_add=True)
    terms_accepted=models.BooleanField(default=False)
    existing_creditcard_holder =models.CharField(max_length=10,choices=EXIST_CARD_CHOICES)
    card_limit = models.IntegerField(null=True,blank=True,validators=[validate_amount])
    card_belonging_bank_name = models.CharField(max_length=25,null=True,blank=True,validators=[validate_only_letters])

    def __str__(self):
        return f"{self.application_id}"
    def save(self, *args, **kwargs):
        if not self.application_id:
            last_entry = credbasicdetailform.objects.filter(application_id__startswith='SLNCC').aggregate(Max('application_id'))
            last_number = last_entry.get('application_id__max', None)

            if last_number:
                try:
                    last_number_int = int(last_number[5:])  
                    new_number = last_number_int + 1
                except ValueError:
                    new_number = 1001
            else:
                new_number = 1001

            self.application_id = f"SLNCC{new_number:04d}"

        print(f"Saving GoldBasicDetail with application_id: {self.application_id}")
        
        
        super(credbasicdetailform, self).save(*args, **kwargs)
        
class creCibilCheck(models.Model):
    user = models.ForeignKey(credbasicdetailform, on_delete=models.CASCADE)
    otp = models.CharField(max_length=6,default='')
    cibil_score = models.IntegerField(null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    def is_valid(self):
        return self.created_at >= timezone.now() - timedelta(minutes=10)


from datetime import date, timedelta



class CreditDetail(models.Model):
    basicdetailform = models.OneToOneField(credbasicdetailform, on_delete=models.CASCADE)
  
    GENDER_CHOICES = [
        ('FEMALE', 'Female'),
        ('MALE', 'Male'),
        ('OTHER', 'Other'),
    ]

    MARITAL_STATUS_CHOICES = [
        ('SINGLE', 'Single'),
        ('MARRIED', 'Married'),
    ]

    COMPANY_TYPE_CHOICES = [
        ('PUBLIC', 'Public'),
        ('PRIVATE', 'Private'),
        ('GOVERNMENT', 'Government'),
        ('SELF_EMPLOYED', 'Self-employed'),
        ('OTHER', 'Other'),
    ]
    own_house = [
        ('YES', 'Yes'),
        ('NO', 'No'),
    ]
    address = [
        ('RENT', 'Rent'),
        ('OWN', 'Own'),

    ]
    first_name = models.CharField(max_length=100, validators=[validate_only_letters])  # Required
    last_name = models.CharField(max_length=100, validators=[validate_only_letters])  # Required
    gender = models.CharField(max_length=10, choices=GENDER_CHOICES)  # Required
    father_name = models.CharField(max_length=100, validators=[validate_only_letters])  # Required
    date_of_birth = models.DateField(validators=[validate_date])  # Required
    mobile_number = models.CharField(max_length=10, validators=[validate_mobile_number])  # Required
    pan_card_number = models.CharField(max_length=10, validators=[validate_pan])  # Required
    aadhar_card_number = models.CharField(max_length=12, validators=[validate_aadhar_number])  # Required
    marital_status = models.CharField(max_length=10, choices=MARITAL_STATUS_CHOICES)  # Required
    email = models.EmailField(validators=[validate_email])  # Required
    current_address = models.TextField(validators=[validate_address])  # Required
    current_address_type = models.TextField(choices=address)
    current_address_pincode = models.CharField(max_length=6, validators=[validate_pincode])  # Required
    aadhar_address_type = models.TextField(choices=address)
    aadhar_address = models.TextField(validators=[validate_address])  # Required
    aadhar_pincode = models.CharField(max_length=6, validators=[validate_pincode])  # Required
    running_emis = models.CharField(max_length=10, validators=[validate_amount])  # Required
    net_salary = models.CharField(max_length=10, validators=[validate_amount])  # Required
    company_name = models.CharField(max_length=100, validators=[validate_only_letters])  # Required
    company_type = models.CharField(max_length=20, choices=COMPANY_TYPE_CHOICES)  # Required
    job_joining_date = models.DateField()  # Required
    job_location = models.CharField(max_length=100)  # Required
    total_job_experience = models.IntegerField()  # Required
    work_email = models.EmailField(validators=[validate_email], blank=True, null=True)  # Optional
    office_address = models.TextField(validators=[validate_address], blank=True, null=True)  # Optional
    office_address_pincode = models.CharField(max_length=6, validators=[validate_pincode])  # Required
    ref1_name = models.CharField(max_length=200, validators=[validate_only_letters])  # Required
    ref1_mobile = models.CharField(max_length=10, validators=[validate_mobile_number])  # Required
    ref2_name = models.CharField(max_length=200, validators=[validate_only_letters], blank=True, null=True)  # Optional
    ref2_mobile = models.CharField(max_length=10, validators=[validate_mobile_number], blank=True, null=True)  # Optional
    own_house = models.CharField(max_length=10,choices=own_house)  # Required
    dsaref_code=models.CharField(max_length=100,null=True,blank=True)

ganesh/templates/credbasicdetail.html
{% extends "links.html" %}

{% block content %}
<style>
    .as{
        color: red;
    }
    .error-message{
        color: red;
    }
</style>
<div class="container mt-4">

    {% if otp %}
    <div class="container mt-5">
        <h2 class="mb-4">Enter OTP</h2>

        <h3 class="text-center mb-4">{{ otp }}</h3>
        <form method="POST" class="text-center">
            {% csrf_token %}
            <div class="form-group col-md-6">
                <input type="text" name="otp" class="form-control" placeholder="Enter OTP" required>
            </div>
            <button type="submit" class="btn btn-primary">Fetch Credit Report</button>
        </form>
    </div>
    
    {% else %}
    <h2 class="text-center" style="background-color: rgb(96, 167, 239); border-radius: 8px; padding: 10px; color: aliceblue;">Basic Detail Application Form</h2>

    <div class="container text-center text-danger">
        {% if form.non_field_errors %}
            <div class="">
                {% for error in form.non_field_errors %}
                    {{ error }}
                {% endfor %}
            </div>
        {% endif %}
    </div>
    {% if messages %}
            <div class="messages">
                {% for message in messages %}
                    <div class="alert {{ message.tags }}">{{ message }}</div>
                {% endfor %}
            </div>
        {% endif %}
    
        <form method="post" action="" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="row">
                <div class="col-md-6">
                    <div class="form-group">
                        <label for="id_fname">FName (As per PAN)<span class='as'>*</span></label>
                        {{ form.fname }}
                        {% if form.fname.errors %}
                            <div class="error-message">
                                {% for error in form.fname.errors %}
                                    {{ error }}
                                {% endfor %}
                            </div>
                        {% endif %}
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="form-group">
                        <label for="id_lname">lName (As per PAN)<span class='as'>*</span></label>
                        {{ form.lname }}
                        {% if form.lname.errors %}
                            <div class="error-message">
                                {% for error in form.lname.errors %}
                                    {{ error }}
                                {% endfor %}
                            </div>
                        {% endif %}
                    </div>
                </div>
                </div>
                <div class="row">
                <div class="col-md-6">
                    <div class="form-group">
                        <label for="id_pan_num">PAN Number<span class='as'>*</span></label>
                        {{ form.pan_num }}
                        {% if form.pan_num.errors %}
                            <div class="error-message">
                                {% for error in form.pan_num.errors %}
                                    {{ error }}
                                {% endfor %}
                            </div>
                        {% endif %}
                    </div>
                </div>
            
            
                <div class="col-md-6">
                    <div class="form-group">
                        <label for="id_Aadhar_number">Aadhar Number<span class='as'>*</span></label>
                        {{ form.Aadhar_number }}
                        {% if form.Aadhar_number.errors %}
                            <div class="error-message">
                                {% for error in form.Aadhar_number.errors %}
                                    {{ error }}
                                {% endfor %}
                            </div>
                        {% endif %}
                    </div>
                </div>
               
               
<div class="col-md-6">
    <div class="form-group">
        <label for="id_phone_number">Mobile Number<span class='as'>*</span></label>
        <input type="text" id="id_phone_number" name="phone_number" required oninput="saveMobileNumber(this.value)" class="form-control">
        {% if form.phone_number.errors %}
            <div class="error-message">
                {% for error in form.phone_number.errors %}
                    {{ error }}
                {% endfor %}
            </div>
        {% endif %}
    </div>
</div>
              
                

                <div class="col-md-6">
                    <div class="form-group">
                        <label for="id_gender">Gender</label>
                        {{ form.gender }}
                        {% if form.gender.errors %}
                            <div class="error-message">
                                {% for error in form.gender.errors %}
                                    {{ error }}
                                {% endfor %}
                            </div>
                        {% endif %}
                    </div>
                </div>
                </div>

                
                <div class="row">
                <div class="col-md-6">
                    <div class="form-group">
                        <label for="id_email">Email</label>
                        {{ form.email }}
                        {% if form.email.errors %}
                            <div class="error-message">
                                {% for error in form.email.errors %}
                                    {{ error }}
                                {% endfor %}
                            </div>
                        {% endif %}
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="form-group">
                        <label for="id_Dob">Date of Birth<span class='as'>*</span></label>
                        {{ form.Dob }}
                        {% if form.Dob.errors %}
                            <div class="error-message">
                                {% for error in form.Dob.errors %}
                                    {{ error }}
                                {% endfor %}
                            </div>
                        {% endif %}
                    </div>
                </div>
                </div>
                <div class="row">
                <div class="col-md-6">
                    <div class="form-group">
                        <label for="id_marital_status">Marital Status</label>
                        {{ form.marital_status }}
                        {% if form.marital_status.errors %}
                            <div class="error-message">
                                {% for error in form.marital_status.errors %}
                                    {{ error }}
                                {% endfor %}
                            </div>
                        {% endif %}
                    </div>
                </div>
            
                <div class="col-md-6">
                    <div class="form-group">
                        <label for="id_existing_creditcard_holder">Existing Creditcard Holder</label>
                        {{ form.existing_creditcard_holder }}
                        {% if form.existing_creditcard_holder.errors %}
                            <div class="error-message">
                                {% for error in form.existing_creditcard_holder.errors %}
                                    <div>{{ error }}</div>
                                {% endfor %}
                            </div>
                        {% endif %}
                    </div>
                </div>
            </div>
    
            <!-- Additional fields for existing credit card holders -->
            <div id="credit-card-fields" class="d-none">
                <div class="row">
                    <div class="col-md-6">
                        <div class="form-group">
                            <label for="id_card_limit">Card Limit</label>
                            {{ form.card_limit }}
                            {% if form.card_limit.errors %}
                                <div class="error-message">
                                    {% for error in form.card_limit.errors %}
                                        <div>{{ error }}</div>
                                    {% endfor %}
                                </div>
                            {% endif %}
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="form-group">
                            <label for="id_card_belonging_bank_name">Card Belonging Bank Name</label>
                            {{ form.card_belonging_bank_name }}
                            {% if form.card_belonging_bank_name.errors %}
                                <div class="error-message">
                                    {% for error in form.card_belonging_bank_name.errors %}
                                        <div>{{ error }}</div>
                                    {% endfor %}
                                </div>
                            {% endif %}
                        </div>
                    </div>
                </div>
            </div>
    
            <div class="form-check mt-4">
                {{ form.terms_accepted }}
                <label class="form-check-label" for="id_terms_accepted">Accept Terms and Conditions</label>
                {% if form.terms_accepted.errors %}
                    <div class="error-message">
                        {% for error in form.terms_accepted.errors %}
                            <div>{{ error }}</div>
                        {% endfor %}
                    </div>
                {% endif %}
            </div>
           
            <button type="submit" class="btn btn-primary mt-3 col-md-8 offset-md-3">Submit</button>
        </form>
    
        <script>
            document.querySelector('#id_existing_creditcard_holder').addEventListener('change', function() {
                var isExistingHolder = this.value === "YES";
                document.getElementById('credit-card-fields').classList.toggle('d-none', !isExistingHolder);
                document.querySelector('#id_card_belonging_bank_name').required = isExistingHolder;
                document.querySelector('#id_card_limit').required = isExistingHolder;
            });
        </script>
    
        
    </div>
    
    
    
                 </form>
    {% endif %}
</div>

<script>
    document.addEventListener('DOMContentLoaded', function() {
        function clearErrorMessages(field) {
            var parent = field.closest('.form-group');
            if (parent) {
                var errorFeedback = parent.querySelector('.error-message');
                if (errorFeedback) {
                    errorFeedback.innerHTML = '';
                }
            }
        }

        var fields = document.querySelectorAll('.form-group input, .form-group select, .form-group textarea');
        fields.forEach(function(field) {
            field.addEventListener('input', function() {
                clearErrorMessages(this);
            });
        });
    });
    
    document.addEventListener('DOMContentLoaded', function () {
        document.querySelectorAll('#id_phone_number,#id_Aadhar_number').forEach((s) => {
            s.addEventListener('input', function (e) {
                var value = e.target.value;
                e.target.value = value.replace(/[^0-9]/g, '');
            });
        });
    });

    document.addEventListener('DOMContentLoaded', function() {
    var panNumberField = document.getElementById('id_pan_num');
    panNumberField.addEventListener('input', function() {
        var value = this.value;
        this.value = value.replace(/[^A-Z0-9]/g, '');
    });
});

document.addEventListener('DOMContentLoaded', function () {
        document.querySelectorAll('#id_fname,#id_lname').forEach((s) => {
            s.addEventListener('input', function (e) {
                var value = e.target.value;
                e.target.value = value.replace(/[^A-Za-z]/g, '');
            });
        });
    });

document.getElementById('id_phone_number').addEventListener('input', function() {
    if (this.value.length > 10) {
        this.value = this.value.slice(0, 10);
    }
});

</script>




  
<script>
    function saveMobileNumber(value) {
        localStorage.setItem('mobileNumber', value);
    }
</script>
<script>
    window.addEventListener('message', function(event) {
     
        if (event.data === 'Apply custom styles') {
            document.body.style.backgroundColor = 'white';
    
    
            var style = document.createElement('style');
            style.innerHTML = `
               body::-webkit-scrollbar{
               display:none;
               }
            `;
            document.head.appendChild(style);
        
       }
    });
</script>





{% endblock %}

ganesh/templates/credit_update.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=, initial-scale=1.0">
    <title>credit application update</title>
</head>
<body>
    <div class="container">
        <form action="">
            {% csrf_token %}
            {{form.as_p}}


        <button>update</button>


        </form>

    </div>
</body>
</html>